#!/usr/bin/env python3
"""Regenerate LATEST.md for sporaxis from the latest attested release.

This is the ONLY allowed writer of LATEST.md (PROVENANCE.md Rule 2/3). It is
called by `.github/workflows/update-latest-md.yml` AFTER `gh attestation verify`
has accepted the release tarball — never by hand. It renders the whole file.

With TAG + DIGEST set, it advertises that release. Without them it renders the
honest "no attested release published yet" bootstrap state, so a manual run can
never invent a version.

Env:
  REPO     owner/repo (default: $GITHUB_REPOSITORY, else sporaxis-com/sporaxis)
  TAG      release tag to advertise, e.g. v0.0.2. Omit -> bootstrap placeholder.
  DIGEST   sha256:... of the verified tarball (required with TAG).
  TARBALL  asset filename (default: sporaxis-x86_64-unknown-linux-gnu.tar.gz)
  TARGET   rust target-triple label (default: x86_64-unknown-linux-gnu)
  GH_TOKEN GitHub token with contents:read (for `gh release view`)

Output: full LATEST.md on stdout.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys


def env(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip()


def release_published_at(repo: str, tag: str) -> str:
    """Return the release's publish timestamp as 'YYYY-MM-DD HH:MM:SS', or ''."""
    try:
        out = subprocess.run(
            ["gh", "release", "view", tag, "--repo", repo, "--json", "publishedAt"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout
        ts = json.loads(out).get("publishedAt", "")
        return ts.replace("T", " ").replace("Z", "").split(".")[0]
    except (subprocess.CalledProcessError, json.JSONDecodeError):
        return ""


BOOTSTRAP = """## sporaxis CLI

> **No attested release published yet.**
>
> The bootstrap release `v0.0.1` is the first tag pushed after the attested
> release pipeline existed; its workflow run is the first to issue an attestation.
> Until that run completes and `gh attestation verify` accepts the tarball, this
> file does not advertise a version. Track build status on the
> [Actions tab](https://github.com/sporaxis-com/sporaxis/actions); see all
> releases at [Releases](https://github.com/sporaxis-com/sporaxis/releases)."""


def advertised(repo: str, tag: str, digest: str, tarball: str, target: str) -> str:
    created = release_published_at(repo, tag) or "—"
    return f"""## sporaxis CLI — `{tag}`

`curl -fsSL https://github.com/{repo}/releases/latest/download/{tarball} | tar -xz`

| Target | Tarball | Digest | Released (UTC) |
|--------|---------|--------|----------------|
| {target} | `{tarball}` | `{digest}` | {created} |

|             |                                                                   |
|-------------|-------------------------------------------------------------------|
| Release     | https://github.com/{repo}/releases/tag/{tag}                      |
| Provenance  | SLSA Build Provenance v1 — `gh attestation verify {tarball} --repo {repo}` |"""


def main() -> None:
    repo = env("REPO") or env("GITHUB_REPOSITORY") or "sporaxis-com/sporaxis"
    tag = env("TAG")
    digest = env("DIGEST")
    tarball = env("TARBALL") or "sporaxis-x86_64-unknown-linux-gnu.tar.gz"
    target = env("TARGET") or "x86_64-unknown-linux-gnu"

    if tag and not digest:
        raise SystemExit("DIGEST is required when TAG is set (verify before render)")

    section = advertised(repo, tag, digest, tarball, target) if tag else BOOTSTRAP

    out = f"""<!--
  This file advertises the latest ATTESTED release artifact of sporaxis.
  Policy: PROVENANCE.md Rule 2 — a version appears here only after
  `gh attestation verify` has accepted its release tarball. No version is ever
  hand-written in. Generated by .github/workflows/update-latest-md.yml +
  tools/render-latest-md.py; do NOT edit by hand — the next workflow run
  overwrites it.
-->

# sporaxis — latest published artifact

`sporaxis` publishes one surface: a self-contained `sporaxis` CLI binary, shipped
as a GitHub **Release tarball** with an SLSA Build Provenance v1 attestation. (No
GHCR image — `sporaxis` is the engine, not a bundle.)

{section}

## Pin policy

- Tagged releases are immutable; version numbers are monotonic and never reused
  (a failed attempt retires its number — see [`PROVENANCE.md`](./PROVENANCE.md)).
- Every release ships a verifiable **SLSA Build Provenance v1** attestation tying
  the tarball to a specific GitHub Actions run on this repo. Workstation pushes
  are not permitted; this file does not advance unless `gh attestation verify`
  accepts the new tarball.
- Today's coverage is `x86_64-unknown-linux-gnu`. Additional targets are tracked
  on the [project board](https://github.com/sporaxis-com/sporaxis).

See [`PROVENANCE.md`](./PROVENANCE.md) for the full release policy, and the
[Releases page](https://github.com/sporaxis-com/sporaxis/releases) for
auto-generated per-version notes.
"""
    sys.stdout.write(out)


if __name__ == "__main__":
    main()
